### ISSUE TITLE
Cannot get good froc

### ISSUE THREAD

**Issue by vfishc** [M3DV/FracNet#9]
I'm sorry , using your code I don't get good froc ,and it's only about 0.38.Are there some errors ?

**Comment by kaimingkuang** [comment]
Since we're also the host of [the RibFrac Challenge](https://ribfrac.grand-challenge.org/overview/), it is not viable for us to release the complete version of FracNet due to risks of data leakage. This is a duplicate issue of #8.  You may refer to this previous issue for some performance improving tips.

**Comment by BelieferQAQ** [comment]
> I'm sorry , using your code I don't get good froc ,and it's only about 0.38.Are there some errors ?

Hello, I have encountered the same problem. Can I add your QQ and discuss it? Thank you very much. My qq318831418
